#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

# actions to do

event_templates('nethserver-lemonldap-ng-update', qw(
		/etc/lemonldap-ng/lemonldap-ng.ini
		/etc/httpd/conf.d/z-lemonldap-ng-manager.conf
		/etc/httpd/conf.d/z-lemonldap-ng-portal.conf
		/root/lemon_config.sh
));

event_actions('nethserver-lemonldap-ngs-update', qw(
		initialize-default-databases 00
		runlevel-adjust 10'
));
		
event_services('nethserver-lemonldap-ng-update', qw(
               httpd reload
));
